CREATE TABLE "rihno_metrics" (
  "time" timestamptz NOT NULL,
  "agent_id" text NOT NULL,
  "email" text NOT NULL,
  "agent_name" text NOT NULL,
  "agent_type" text NOT NULL,
  "process_count" int DEFAULT 0,
  "process_creation_rate" int DEFAULT 0,
  "process_termination_rate" int DEFAULT 0,
  "high_cpu_process_count" int DEFAULT 0,
  "high_mem_process_count" int DEFAULT 0,
  "avg_process_cpu" float DEFAULT 0,
  "avg_process_memory" float DEFAULT 0,
  "avg_process_rss" bigint DEFAULT 0,
  "avg_process_vms" bigint DEFAULT 0,
  "total_threads" int DEFAULT 0,
  "zombie_process_count" int DEFAULT 0,
  "root_process_count" int DEFAULT 0,
  "avg_process_age_seconds" float DEFAULT 0,
  "process_with_many_threads" int DEFAULT 0,
  "suspicious_process_names" int DEFAULT 0,
  "total_file_descriptors" int DEFAULT 0,
  "system_cpu" float DEFAULT 0,
  "avg_core_cpu" float DEFAULT 0,
  "system_memory_percent" float DEFAULT 0,
  "system_memory_used" bigint DEFAULT 0,
  "system_memory_available" bigint DEFAULT 0,
  "system_memory_total" bigint DEFAULT 0,
  "swap_used_percent" float DEFAULT 0,
  "swap_total" bigint DEFAULT 0,
  "swap_used" bigint DEFAULT 0,
  "disk_read_bytes" bigint DEFAULT 0,
  "disk_write_bytes" bigint DEFAULT 0,
  "disk_read_rate" float DEFAULT 0,
  "disk_write_rate" float DEFAULT 0,
  "disk_read_count" bigint DEFAULT 0,
  "disk_write_count" bigint DEFAULT 0,
  "disk_io_rate" float DEFAULT 0,
  "logged_in_users" int DEFAULT 0,
  "system_uptime" bigint DEFAULT 0,
  "system_boot_time" bigint DEFAULT 0,
  "cpu_usage_spike" float DEFAULT 0,
  "memory_usage_spike" float DEFAULT 0,
  "total_connections" int DEFAULT 0,
  "tcp_connections" int DEFAULT 0,
  "udp_connections" int DEFAULT 0,
  "established_connections" int DEFAULT 0,
  "listen_connections" int DEFAULT 0,
  "time_wait_connections" int DEFAULT 0,
  "syn_sent_connections" int DEFAULT 0,
  "syn_recv_connections" int DEFAULT 0,
  "close_wait_connections" int DEFAULT 0,
  "fin_wait_connections" int DEFAULT 0,
  "net_bytes_sent" bigint DEFAULT 0,
  "net_bytes_recv" bigint DEFAULT 0,
  "net_packets_sent" bigint DEFAULT 0,
  "net_packets_recv" bigint DEFAULT 0,
  "net_errors_in" bigint DEFAULT 0,
  "net_errors_out" bigint DEFAULT 0,
  "net_drops_in" bigint DEFAULT 0,
  "net_drops_out" bigint DEFAULT 0,
  "net_send_rate" float DEFAULT 0,
  "net_recv_rate" float DEFAULT 0,
  "net_packet_send_rate" float DEFAULT 0,
  "net_packet_recv_rate" float DEFAULT 0,
  "unique_source_ips" int DEFAULT 0,
  "unique_dest_ips" int DEFAULT 0,
  "new_source_ips" int DEFAULT 0,
  "private_ip_connections" int DEFAULT 0,
  "public_ip_connections" int DEFAULT 0,
  "top_source_ip_count" int DEFAULT 0,
  "top_source_ip" text DEFAULT '',
  "unique_local_ports" int DEFAULT 0,
  "unique_remote_ports" int DEFAULT 0,
  "well_known_port_connections" int DEFAULT 0,
  "ephemeral_port_connections" int DEFAULT 0,
  "suspicious_port_connections" int DEFAULT 0,
  "port_scan_indicators" int DEFAULT 0,
  "tcp_ratio" float DEFAULT 0,
  "udp_ratio" float DEFAULT 0,
  "tcp_udp_ratio" float DEFAULT 0,
  "processes_with_net_activity" int DEFAULT 0,
  "avg_connections_per_process" float DEFAULT 0,
  "connection_creation_rate" int DEFAULT 0,
  "connection_termination_rate" int DEFAULT 0,
  "external_ip_count" int DEFAULT 0,
  "loopback_connections" int DEFAULT 0,
  "broadcast_connections" int DEFAULT 0,
  "connection_churn_rate" float DEFAULT 0,
  "connection_density" float DEFAULT 0,
  "port_scanning_score" float DEFAULT 0,
  "data_exfiltration_score" float DEFAULT 0,
  "bandwidth_asymmetry" float DEFAULT 0,
  "c2_communication_score" float DEFAULT 0,
  "failed_connection_ratio" float DEFAULT 0,
  "total_incoming_connections" int DEFAULT 0,
  "total_outgoing_connections" int DEFAULT 0,
  "unique_incoming_ips" int DEFAULT 0,
  "unique_outgoing_ips" int DEFAULT 0,
  "local_ips_count" int DEFAULT 0
);

CREATE TABLE "rihno_network_maps" (
  "time" timestamptz NOT NULL,
  "agent_id" text NOT NULL,
  "email" text NOT NULL,
  "agent_name" text NOT NULL,
  "network_map_json" jsonb NOT NULL
);

CREATE TABLE "rihno_connections" (
  "time" timestamptz NOT NULL,
  "agent_id" text NOT NULL,
  "agent_name" text NOT NULL,
  "remote_ip" text NOT NULL,
  "remote_port" int NOT NULL,
  "local_ip" text NOT NULL,
  "local_port" int NOT NULL,
  "protocol" text NOT NULL,
  "state" text NOT NULL,
  "pid" int DEFAULT 0,
  "process_name" text DEFAULT '',
  "direction" text NOT NULL,
  "is_private" boolean DEFAULT false,
  "is_loopback" boolean DEFAULT false,
  "is_suspicious" boolean DEFAULT false
);

CREATE TABLE "rihno_alerts" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "time" timestamptz NOT NULL DEFAULT (NOW()),
  "agent_id" text NOT NULL,
  "agent_name" text NOT NULL,
  "email" text NOT NULL,
  "alert_type" text NOT NULL,
  "severity" text NOT NULL,
  "description" text NOT NULL,
  "metric_name" text DEFAULT '',
  "metric_value" float DEFAULT 0,
  "threshold" float DEFAULT 0,
  "acknowledged" boolean DEFAULT false,
  "resolved" boolean DEFAULT false,
  "resolved_at" timestamptz
);

CREATE TABLE "rihno_agents" (
  "agent_id" text PRIMARY KEY,
  "agent_name" text NOT NULL,
  "agent_type" text NOT NULL,
  "email" text NOT NULL,
  "first_seen" timestamptz NOT NULL DEFAULT (NOW()),
  "last_seen" timestamptz NOT NULL DEFAULT (NOW()),
  "is_active" boolean DEFAULT true,
  "os_info" text DEFAULT '',
  "ip_address" text DEFAULT ''
);

CREATE TABLE "rihno_metrics_1min" (
  "bucket" timestamptz NOT NULL,
  "agent_id" text NOT NULL,
  "agent_name" text NOT NULL,
  "email" text NOT NULL,
  "avg_cpu" float,
  "max_cpu" float,
  "avg_memory" float,
  "max_memory" float,
  "avg_connections" float,
  "max_connections" float,
  "total_suspicious_ports" bigint,
  "total_suspicious_processes" bigint,
  "avg_net_send_rate" float,
  "avg_net_recv_rate" float,
  "max_port_scan_score" float,
  "max_exfil_score" float,
  "max_c2_score" float,
  "avg_churn_rate" float,
  "avg_bandwidth_asymmetry" float,
  "avg_process_count" float,
  "max_process_count" float,
  "avg_disk_io_rate" float
);

CREATE TABLE "rihno_metrics_1hr" (
  "bucket" timestamptz NOT NULL,
  "agent_id" text NOT NULL,
  "agent_name" text NOT NULL,
  "email" text NOT NULL,
  "avg_cpu" float,
  "max_cpu" float,
  "min_cpu" float,
  "avg_memory" float,
  "max_memory" float,
  "avg_connections" float,
  "max_connections" float,
  "total_suspicious_ports" bigint,
  "total_suspicious_processes" bigint,
  "avg_net_send_rate" float,
  "avg_net_recv_rate" float,
  "max_port_scan_score" float,
  "max_exfil_score" float,
  "max_c2_score" float,
  "avg_process_count" float,
  "avg_disk_io_rate" float,
  "sample_count" bigint
);

CREATE INDEX "idx_metrics_agent_id" ON "rihno_metrics" ("agent_id", "time");

CREATE INDEX "idx_metrics_email" ON "rihno_metrics" ("email", "time");

CREATE INDEX "idx_metrics_agent_name" ON "rihno_metrics" ("agent_name", "time");

CREATE INDEX "idx_netmap_agent" ON "rihno_network_maps" ("agent_id", "time");

CREATE INDEX "idx_conn_agent" ON "rihno_connections" ("agent_id", "time");

CREATE INDEX "idx_conn_remote_ip" ON "rihno_connections" ("remote_ip", "time");

CREATE INDEX "idx_conn_direction" ON "rihno_connections" ("direction", "time");

CREATE INDEX "idx_alerts_agent" ON "rihno_alerts" ("agent_id", "time");

CREATE INDEX "idx_alerts_severity" ON "rihno_alerts" ("severity", "time");

CREATE INDEX "idx_agents_email" ON "rihno_agents" ("email");

CREATE INDEX "idx_agents_active" ON "rihno_agents" ("is_active");

COMMENT ON TABLE "rihno_metrics" IS 'TimescaleDB hypertable partitioned by time. Compressed after 2 days. Retained 30 days.';

COMMENT ON COLUMN "rihno_metrics"."time" IS 'Collection timestamp (hypertable partition key)';

COMMENT ON COLUMN "rihno_metrics"."agent_id" IS 'TCP address of the agent e.g. 192.168.1.5:49832';

COMMENT ON COLUMN "rihno_metrics"."email" IS 'User email from agent config';

COMMENT ON COLUMN "rihno_metrics"."agent_name" IS 'Human-readable agent name';

COMMENT ON COLUMN "rihno_metrics"."agent_type" IS 'Agent type e.g. linux, windows, macos';

COMMENT ON COLUMN "rihno_metrics"."process_count" IS 'Total running processes';

COMMENT ON COLUMN "rihno_metrics"."process_creation_rate" IS 'New processes since last cycle';

COMMENT ON COLUMN "rihno_metrics"."process_termination_rate" IS 'Terminated processes since last cycle';

COMMENT ON COLUMN "rihno_metrics"."high_cpu_process_count" IS 'Processes using >50% CPU';

COMMENT ON COLUMN "rihno_metrics"."high_mem_process_count" IS 'Processes using >10% memory';

COMMENT ON COLUMN "rihno_metrics"."avg_process_cpu" IS 'Average CPU% across all processes';

COMMENT ON COLUMN "rihno_metrics"."avg_process_memory" IS 'Average memory% across all processes';

COMMENT ON COLUMN "rihno_metrics"."avg_process_rss" IS 'Average resident set size (bytes)';

COMMENT ON COLUMN "rihno_metrics"."avg_process_vms" IS 'Average virtual memory size (bytes)';

COMMENT ON COLUMN "rihno_metrics"."total_threads" IS 'Sum of threads across all processes';

COMMENT ON COLUMN "rihno_metrics"."zombie_process_count" IS 'Zombie/defunct process count';

COMMENT ON COLUMN "rihno_metrics"."root_process_count" IS 'Processes running as root/SYSTEM';

COMMENT ON COLUMN "rihno_metrics"."avg_process_age_seconds" IS 'Average process age in seconds';

COMMENT ON COLUMN "rihno_metrics"."process_with_many_threads" IS 'Processes with >100 threads';

COMMENT ON COLUMN "rihno_metrics"."suspicious_process_names" IS 'Processes matching malware name patterns';

COMMENT ON COLUMN "rihno_metrics"."total_file_descriptors" IS 'Total open file descriptors';

COMMENT ON COLUMN "rihno_metrics"."system_cpu" IS 'Overall system CPU usage %';

COMMENT ON COLUMN "rihno_metrics"."avg_core_cpu" IS 'Average per-core CPU usage %';

COMMENT ON COLUMN "rihno_metrics"."system_memory_percent" IS 'System memory usage %';

COMMENT ON COLUMN "rihno_metrics"."system_memory_used" IS 'Used memory in bytes';

COMMENT ON COLUMN "rihno_metrics"."system_memory_available" IS 'Available memory in bytes';

COMMENT ON COLUMN "rihno_metrics"."system_memory_total" IS 'Total memory in bytes';

COMMENT ON COLUMN "rihno_metrics"."swap_used_percent" IS 'Swap usage %';

COMMENT ON COLUMN "rihno_metrics"."swap_total" IS 'Total swap in bytes';

COMMENT ON COLUMN "rihno_metrics"."swap_used" IS 'Used swap in bytes';

COMMENT ON COLUMN "rihno_metrics"."disk_read_bytes" IS 'Cumulative disk bytes read';

COMMENT ON COLUMN "rihno_metrics"."disk_write_bytes" IS 'Cumulative disk bytes written';

COMMENT ON COLUMN "rihno_metrics"."disk_read_rate" IS 'Disk read bytes/sec';

COMMENT ON COLUMN "rihno_metrics"."disk_write_rate" IS 'Disk write bytes/sec';

COMMENT ON COLUMN "rihno_metrics"."disk_read_count" IS 'Cumulative disk read operations';

COMMENT ON COLUMN "rihno_metrics"."disk_write_count" IS 'Cumulative disk write operations';

COMMENT ON COLUMN "rihno_metrics"."disk_io_rate" IS 'Combined read+write bytes/sec';

COMMENT ON COLUMN "rihno_metrics"."logged_in_users" IS 'Number of logged-in users';

COMMENT ON COLUMN "rihno_metrics"."system_uptime" IS 'System uptime in seconds';

COMMENT ON COLUMN "rihno_metrics"."system_boot_time" IS 'Boot time as unix timestamp';

COMMENT ON COLUMN "rihno_metrics"."cpu_usage_spike" IS 'CPU delta from previous reading';

COMMENT ON COLUMN "rihno_metrics"."memory_usage_spike" IS 'Memory delta from previous reading';

COMMENT ON COLUMN "rihno_metrics"."total_connections" IS 'Total network connections';

COMMENT ON COLUMN "rihno_metrics"."tcp_connections" IS 'TCP connection count';

COMMENT ON COLUMN "rihno_metrics"."udp_connections" IS 'UDP connection count';

COMMENT ON COLUMN "rihno_metrics"."established_connections" IS 'ESTABLISHED state count';

COMMENT ON COLUMN "rihno_metrics"."listen_connections" IS 'LISTEN state count';

COMMENT ON COLUMN "rihno_metrics"."time_wait_connections" IS 'TIME_WAIT state count';

COMMENT ON COLUMN "rihno_metrics"."syn_sent_connections" IS 'SYN_SENT state count';

COMMENT ON COLUMN "rihno_metrics"."syn_recv_connections" IS 'SYN_RECV state count';

COMMENT ON COLUMN "rihno_metrics"."close_wait_connections" IS 'CLOSE_WAIT state count';

COMMENT ON COLUMN "rihno_metrics"."fin_wait_connections" IS 'FIN_WAIT1+FIN_WAIT2 state count';

COMMENT ON COLUMN "rihno_metrics"."net_bytes_sent" IS 'Cumulative bytes sent';

COMMENT ON COLUMN "rihno_metrics"."net_bytes_recv" IS 'Cumulative bytes received';

COMMENT ON COLUMN "rihno_metrics"."net_packets_sent" IS 'Cumulative packets sent';

COMMENT ON COLUMN "rihno_metrics"."net_packets_recv" IS 'Cumulative packets received';

COMMENT ON COLUMN "rihno_metrics"."net_errors_in" IS 'Inbound NIC errors';

COMMENT ON COLUMN "rihno_metrics"."net_errors_out" IS 'Outbound NIC errors';

COMMENT ON COLUMN "rihno_metrics"."net_drops_in" IS 'Inbound dropped packets';

COMMENT ON COLUMN "rihno_metrics"."net_drops_out" IS 'Outbound dropped packets';

COMMENT ON COLUMN "rihno_metrics"."net_send_rate" IS 'Send rate bytes/sec';

COMMENT ON COLUMN "rihno_metrics"."net_recv_rate" IS 'Receive rate bytes/sec';

COMMENT ON COLUMN "rihno_metrics"."net_packet_send_rate" IS 'Send rate packets/sec';

COMMENT ON COLUMN "rihno_metrics"."net_packet_recv_rate" IS 'Receive rate packets/sec';

COMMENT ON COLUMN "rihno_metrics"."unique_source_ips" IS 'Unique remote IPs seen';

COMMENT ON COLUMN "rihno_metrics"."unique_dest_ips" IS 'Unique local IPs in use';

COMMENT ON COLUMN "rihno_metrics"."new_source_ips" IS 'New remote IPs since last cycle';

COMMENT ON COLUMN "rihno_metrics"."private_ip_connections" IS 'Connections to RFC1918 addresses';

COMMENT ON COLUMN "rihno_metrics"."public_ip_connections" IS 'Connections to public addresses';

COMMENT ON COLUMN "rihno_metrics"."top_source_ip_count" IS 'Connection count of busiest remote IP';

COMMENT ON COLUMN "rihno_metrics"."top_source_ip" IS 'IP address of busiest remote peer';

COMMENT ON COLUMN "rihno_metrics"."unique_local_ports" IS 'Unique local ports in use';

COMMENT ON COLUMN "rihno_metrics"."unique_remote_ports" IS 'Unique remote ports contacted';

COMMENT ON COLUMN "rihno_metrics"."well_known_port_connections" IS 'Connections on ports <1024';

COMMENT ON COLUMN "rihno_metrics"."ephemeral_port_connections" IS 'Connections on ports >32768';

COMMENT ON COLUMN "rihno_metrics"."suspicious_port_connections" IS 'Connections on known-bad ports';

COMMENT ON COLUMN "rihno_metrics"."port_scan_indicators" IS 'IPs touching >10 local ports';

COMMENT ON COLUMN "rihno_metrics"."tcp_ratio" IS 'TCP connections / total';

COMMENT ON COLUMN "rihno_metrics"."udp_ratio" IS 'UDP connections / total';

COMMENT ON COLUMN "rihno_metrics"."tcp_udp_ratio" IS 'TCP / UDP ratio';

COMMENT ON COLUMN "rihno_metrics"."processes_with_net_activity" IS 'Processes with open sockets';

COMMENT ON COLUMN "rihno_metrics"."avg_connections_per_process" IS 'Total connections / active processes';

COMMENT ON COLUMN "rihno_metrics"."connection_creation_rate" IS 'New connections since last cycle';

COMMENT ON COLUMN "rihno_metrics"."connection_termination_rate" IS 'Closed connections since last cycle';

COMMENT ON COLUMN "rihno_metrics"."external_ip_count" IS 'Non-RFC1918 remote IPs';

COMMENT ON COLUMN "rihno_metrics"."loopback_connections" IS 'Connections to 127.0.0.0/8';

COMMENT ON COLUMN "rihno_metrics"."broadcast_connections" IS 'Connections to 255.255.255.255';

COMMENT ON COLUMN "rihno_metrics"."connection_churn_rate" IS '(created+terminated)/total';

COMMENT ON COLUMN "rihno_metrics"."connection_density" IS 'Connections per network-active process';

COMMENT ON COLUMN "rihno_metrics"."port_scanning_score" IS 'Composite port scan likelihood 0-100';

COMMENT ON COLUMN "rihno_metrics"."data_exfiltration_score" IS 'Outbound data anomaly score 0-100';

COMMENT ON COLUMN "rihno_metrics"."bandwidth_asymmetry" IS '|send-recv|/(send+recv) 0-1';

COMMENT ON COLUMN "rihno_metrics"."c2_communication_score" IS 'Beaconing regularity score 0-100';

COMMENT ON COLUMN "rihno_metrics"."failed_connection_ratio" IS 'TIME_WAIT / total connections';

COMMENT ON COLUMN "rihno_metrics"."total_incoming_connections" IS 'Incoming IPv4 connections';

COMMENT ON COLUMN "rihno_metrics"."total_outgoing_connections" IS 'Outgoing IPv4 connections';

COMMENT ON COLUMN "rihno_metrics"."unique_incoming_ips" IS 'Unique IPs connecting inbound';

COMMENT ON COLUMN "rihno_metrics"."unique_outgoing_ips" IS 'Unique IPs connected outbound';

COMMENT ON COLUMN "rihno_metrics"."local_ips_count" IS 'Local IP addresses in use';

COMMENT ON TABLE "rihno_network_maps" IS 'TimescaleDB hypertable. Retained 7 days. Contains full network topology snapshots.';

COMMENT ON COLUMN "rihno_network_maps"."time" IS 'Snapshot timestamp';

COMMENT ON COLUMN "rihno_network_maps"."agent_id" IS 'Agent TCP address';

COMMENT ON COLUMN "rihno_network_maps"."email" IS 'User email';

COMMENT ON COLUMN "rihno_network_maps"."agent_name" IS 'Agent name';

COMMENT ON COLUMN "rihno_network_maps"."network_map_json" IS 'Full connection map as JSONB';

COMMENT ON TABLE "rihno_connections" IS 'TimescaleDB hypertable. Compressed after 2 days. Retained 7 days.';

COMMENT ON COLUMN "rihno_connections"."time" IS 'Collection timestamp';

COMMENT ON COLUMN "rihno_connections"."agent_id" IS 'Agent TCP address';

COMMENT ON COLUMN "rihno_connections"."agent_name" IS 'Agent name';

COMMENT ON COLUMN "rihno_connections"."remote_ip" IS 'Remote peer IP address';

COMMENT ON COLUMN "rihno_connections"."remote_port" IS 'Remote peer port';

COMMENT ON COLUMN "rihno_connections"."local_ip" IS 'Local IP address';

COMMENT ON COLUMN "rihno_connections"."local_port" IS 'Local port';

COMMENT ON COLUMN "rihno_connections"."protocol" IS 'TCP or UDP';

COMMENT ON COLUMN "rihno_connections"."state" IS 'TCP state e.g. ESTABLISHED, LISTEN';

COMMENT ON COLUMN "rihno_connections"."pid" IS 'Process ID owning this socket';

COMMENT ON COLUMN "rihno_connections"."process_name" IS 'Process name owning this socket';

COMMENT ON COLUMN "rihno_connections"."direction" IS 'incoming or outgoing';

COMMENT ON COLUMN "rihno_connections"."is_private" IS 'Remote IP is RFC1918';

COMMENT ON COLUMN "rihno_connections"."is_loopback" IS 'Remote IP is 127.0.0.0/8';

COMMENT ON COLUMN "rihno_connections"."is_suspicious" IS 'Connection uses a known-bad port';

COMMENT ON TABLE "rihno_alerts" IS 'TimescaleDB hypertable. Retained 90 days. Severity: low/medium/high/critical.';

COMMENT ON COLUMN "rihno_alerts"."id" IS 'Auto-incrementing alert ID';

COMMENT ON COLUMN "rihno_alerts"."time" IS 'Alert generation time';

COMMENT ON COLUMN "rihno_alerts"."agent_id" IS 'Agent that triggered the alert';

COMMENT ON COLUMN "rihno_alerts"."agent_name" IS 'Agent name';

COMMENT ON COLUMN "rihno_alerts"."email" IS 'User email for notification';

COMMENT ON COLUMN "rihno_alerts"."alert_type" IS 'e.g. HIGH_CPU, PORT_SCAN, C2_COMMUNICATION';

COMMENT ON COLUMN "rihno_alerts"."severity" IS 'low, medium, high, critical';

COMMENT ON COLUMN "rihno_alerts"."description" IS 'Human-readable alert description';

COMMENT ON COLUMN "rihno_alerts"."metric_name" IS 'Which metric triggered this alert';

COMMENT ON COLUMN "rihno_alerts"."metric_value" IS 'Actual metric value at trigger time';

COMMENT ON COLUMN "rihno_alerts"."threshold" IS 'Threshold that was exceeded';

COMMENT ON COLUMN "rihno_alerts"."acknowledged" IS 'Operator has seen this alert';

COMMENT ON COLUMN "rihno_alerts"."resolved" IS 'Alert condition no longer active';

COMMENT ON COLUMN "rihno_alerts"."resolved_at" IS 'When the alert was resolved';

COMMENT ON TABLE "rihno_agents" IS 'Regular table (not hypertable). One row per agent. Updated via UPSERT.';

COMMENT ON COLUMN "rihno_agents"."agent_id" IS 'Agent TCP address (primary key)';

COMMENT ON COLUMN "rihno_agents"."agent_name" IS 'Human-readable agent name';

COMMENT ON COLUMN "rihno_agents"."agent_type" IS 'OS type: linux, windows, macos';

COMMENT ON COLUMN "rihno_agents"."email" IS 'Owner email address';

COMMENT ON COLUMN "rihno_agents"."first_seen" IS 'First connection time';

COMMENT ON COLUMN "rihno_agents"."last_seen" IS 'Most recent heartbeat';

COMMENT ON COLUMN "rihno_agents"."is_active" IS 'Currently connected and sending data';

COMMENT ON COLUMN "rihno_agents"."os_info" IS 'OS version string';

COMMENT ON COLUMN "rihno_agents"."ip_address" IS 'Agent IP address';

COMMENT ON TABLE "rihno_metrics_1min" IS 'Continuous aggregate. Refreshed every 1 min. Retained 7 days.';

COMMENT ON COLUMN "rihno_metrics_1min"."bucket" IS '1-minute time bucket';

COMMENT ON COLUMN "rihno_metrics_1min"."avg_cpu" IS 'AVG(system_cpu) per minute';

COMMENT ON COLUMN "rihno_metrics_1min"."max_cpu" IS 'MAX(system_cpu) per minute';

COMMENT ON COLUMN "rihno_metrics_1min"."avg_memory" IS 'AVG(system_memory_percent)';

COMMENT ON COLUMN "rihno_metrics_1min"."max_memory" IS 'MAX(system_memory_percent)';

COMMENT ON COLUMN "rihno_metrics_1min"."avg_connections" IS 'AVG(total_connections)';

COMMENT ON COLUMN "rihno_metrics_1min"."max_connections" IS 'MAX(total_connections)';

COMMENT ON COLUMN "rihno_metrics_1min"."total_suspicious_ports" IS 'SUM(suspicious_port_connections)';

COMMENT ON COLUMN "rihno_metrics_1min"."total_suspicious_processes" IS 'SUM(suspicious_process_names)';

COMMENT ON COLUMN "rihno_metrics_1min"."avg_net_send_rate" IS 'AVG(net_send_rate)';

COMMENT ON COLUMN "rihno_metrics_1min"."avg_net_recv_rate" IS 'AVG(net_recv_rate)';

COMMENT ON COLUMN "rihno_metrics_1min"."max_port_scan_score" IS 'MAX(port_scanning_score)';

COMMENT ON COLUMN "rihno_metrics_1min"."max_exfil_score" IS 'MAX(data_exfiltration_score)';

COMMENT ON COLUMN "rihno_metrics_1min"."max_c2_score" IS 'MAX(c2_communication_score)';

COMMENT ON COLUMN "rihno_metrics_1min"."avg_churn_rate" IS 'AVG(connection_churn_rate)';

COMMENT ON COLUMN "rihno_metrics_1min"."avg_bandwidth_asymmetry" IS 'AVG(bandwidth_asymmetry)';

COMMENT ON COLUMN "rihno_metrics_1min"."avg_process_count" IS 'AVG(process_count)';

COMMENT ON COLUMN "rihno_metrics_1min"."max_process_count" IS 'MAX(process_count)';

COMMENT ON COLUMN "rihno_metrics_1min"."avg_disk_io_rate" IS 'AVG(disk_io_rate)';

COMMENT ON TABLE "rihno_metrics_1hr" IS 'Continuous aggregate. Refreshed every 1 hr. Retained 365 days.';

COMMENT ON COLUMN "rihno_metrics_1hr"."bucket" IS '1-hour time bucket';

COMMENT ON COLUMN "rihno_metrics_1hr"."avg_cpu" IS 'AVG(system_cpu) per hour';

COMMENT ON COLUMN "rihno_metrics_1hr"."max_cpu" IS 'MAX(system_cpu) per hour';

COMMENT ON COLUMN "rihno_metrics_1hr"."min_cpu" IS 'MIN(system_cpu) per hour';

COMMENT ON COLUMN "rihno_metrics_1hr"."avg_memory" IS 'AVG(system_memory_percent)';

COMMENT ON COLUMN "rihno_metrics_1hr"."max_memory" IS 'MAX(system_memory_percent)';

COMMENT ON COLUMN "rihno_metrics_1hr"."avg_connections" IS 'AVG(total_connections)';

COMMENT ON COLUMN "rihno_metrics_1hr"."max_connections" IS 'MAX(total_connections)';

COMMENT ON COLUMN "rihno_metrics_1hr"."total_suspicious_ports" IS 'SUM(suspicious_port_connections)';

COMMENT ON COLUMN "rihno_metrics_1hr"."total_suspicious_processes" IS 'SUM(suspicious_process_names)';

COMMENT ON COLUMN "rihno_metrics_1hr"."avg_net_send_rate" IS 'AVG(net_send_rate)';

COMMENT ON COLUMN "rihno_metrics_1hr"."avg_net_recv_rate" IS 'AVG(net_recv_rate)';

COMMENT ON COLUMN "rihno_metrics_1hr"."max_port_scan_score" IS 'MAX(port_scanning_score)';

COMMENT ON COLUMN "rihno_metrics_1hr"."max_exfil_score" IS 'MAX(data_exfiltration_score)';

COMMENT ON COLUMN "rihno_metrics_1hr"."max_c2_score" IS 'MAX(c2_communication_score)';

COMMENT ON COLUMN "rihno_metrics_1hr"."avg_process_count" IS 'AVG(process_count)';

COMMENT ON COLUMN "rihno_metrics_1hr"."avg_disk_io_rate" IS 'AVG(disk_io_rate)';

COMMENT ON COLUMN "rihno_metrics_1hr"."sample_count" IS 'Number of raw rows aggregated';

ALTER TABLE "rihno_metrics" ADD FOREIGN KEY ("agent_id") REFERENCES "rihno_agents" ("agent_id");

ALTER TABLE "rihno_network_maps" ADD FOREIGN KEY ("agent_id") REFERENCES "rihno_agents" ("agent_id");

ALTER TABLE "rihno_connections" ADD FOREIGN KEY ("agent_id") REFERENCES "rihno_agents" ("agent_id");

ALTER TABLE "rihno_alerts" ADD FOREIGN KEY ("agent_id") REFERENCES "rihno_agents" ("agent_id");

ALTER TABLE "rihno_metrics_1min" ADD FOREIGN KEY ("agent_id") REFERENCES "rihno_agents" ("agent_id");

ALTER TABLE "rihno_metrics_1hr" ADD FOREIGN KEY ("agent_id") REFERENCES "rihno_agents" ("agent_id");

ALTER TABLE "rihno_connections" ADD FOREIGN KEY ("agent_id") REFERENCES "rihno_network_maps" ("agent_id");
